Point cloud function
Steenroder/steenroder pull request #16
Opened 2022-03-16 09:51 UTC by ulupo

Fixes #14 and refactors notebooks accordingly.

Important: introduces GUDHI requirement at installation time.

2022-03-16 09:54 UTC, ulupo commented
I'm rerunning all notebooks from scratch (the cyclo-octane one takes very long) and verifying that the barcodes remain the same as in the paper.  Will post screenshots here.

2022-03-16 09:56 UTC, ulupo commented
Klein bottle:

![image](https://user-images.githubusercontent.com/46537483/158564051-ad7d3f5f-f4c4-43fd-9a92-a9bd616b265b.png)

and

![image](https://user-images.githubusercontent.com/46537483/158564172-035905e4-ec6e-4b16-bea7-c2758ccfbdc6.png)

2022-03-16 10:10 UTC, ulupo commented
Cyclo-octane:

![image](https://user-images.githubusercontent.com/46537483/158566523-edbbb42d-f779-492b-b28b-eb3d22239a29.png)
and
![image](https://user-images.githubusercontent.com/46537483/158566856-33feb06d-ad03-449e-bfad-565b3b267b2d.png)

@ammedmar please could you check that these look good, I've run out of time for now.

2022-03-17 10:17 UTC, ulupo commented
@ammedmar I have pushed a plotting function, `plot_diagrams`.

You can test it on the Klein bottle notebook by adding the import line

```python
from steenroder.plotting import plot_diagrams
```

and then e.g. plotting the result of the last computation via

```python
plot_diagrams(barcode[:3], st_barcode[:3], k=1, kind="A")
```

2022-03-21 20:08 UTC, gtauzin requested changes
Lgtm! Just a small comment.

2022-03-21 20:08 UTC, gtauzin commented on steenroder/plotting.py
> +    bc : list of ndarray
The parameter name is barcode.

2022-03-21 21:46 UTC, ulupo commented
Thanks @gtauzin!  I realized I forgot to document `rips_barcodes`, so I just pushed a simple docstring.

2022-03-24 12:33 UTC, ulupo commented
Testing on @ammedmar's machine shows that the plotting function does not work well in all systems.  I think this is a MathJax-related issue because the function tries to produce LaTeX legend labels.  The simplest way to fix this would be to agree on default legend label names that do not require LaTeX, and still allow LaTeX rendering as an option in case people want to try that and it works.

@ammedmar what do you think?  What would be suitable names to replace $\mathcal{H}^i_A$, $\mathcal{H}^i_R$, $\mathrm{im}(Sq^k) \cap \mathcal{H}^i_A$, and $\mathrm{im}(Sq^k) \cap \mathcal{H}^i_R$?

2022-03-24 17:44 UTC, ammedmar commented
Yes, we can drop the LaTeX labels then. How about the following?
$\mathcal{H}^i_A$ --> H^i(abs)
$\mathcal{H}^i_R$ --> H^i(rel)
$\mathrm{im}(Sq^k) \cap \mathcal{H}^i_A$ --> im(Sq^k) in H^i(abs)
$\mathrm{im}(Sq^k) \cap \mathcal{H}^i_R$ --> im(Sq^k) in H^i(rel)

2022-03-24 19:05 UTC, ulupo commented
@ammedmar I have now implemented your suggestion.  Could you please check that the diagrams in the Klein bottle notebook (in this branch) display as expected for you?  They display well at my end.

2022-03-25 08:32 UTC, ammedmar commented
I also tested it on the rpn an cp2 notebooks and it looks good. You were right about tex being the issue.
Two very minor comments:
1. I realized that writing (abs) or (rel) in each line of the legend is maybe not ideal. Maybe one can just write absolute (relative) cohomology once as a title for the legend instead.
2. The legend doesn't seem to scale to fit below the diagonal (see screenshot below).
I don't think this needs to be address in this PR though.

2022-03-25 08:34 UTC, ammedmar commented
![plotting](https://user-images.githubusercontent.com/40343505/160084347-a76b7ee0-f116-43b4-9a4a-55e28a4615ff.png)

2022-03-25 08:34 UTC, ammedmar commented
![Screenshot from 2022-03-25 09-30-48](https://user-images.githubusercontent.com/40343505/160084511-ac10d44e-1cbb-4f9c-a81d-5e1335d827b5.png)

2022-03-25 08:35 UTC, ammedmar approved these changes

2022-03-25 08:38 UTC, ulupo commented
Thanks @ammedmar!

> Maybe one can just write absolute (relative) cohomology once as a title for the legend instead.

This is a good idea and would be one easy commit.

> The legend doesn't seem to scale to fit below the diagonal (see screenshot below).

This is harder and I'd indeed leave it to another PR -- I just note that one can make the whole figure bigger as a temporary fix.

2022-03-25 20:45 UTC, ulupo commented
@ammedmar I've made the change.  Let me know if happy to merge!

2022-03-26 09:21 UTC, ammedmar commented
Yes, it looks good!

2022-03-26 09:22 UTC, merged